# More NumPy Features

In [2]:
import numpy as np

## Assignment with slicing

You can use the slice syntax that we used before to get 'slices' of a list or array in order to actually assign new elements to those spots.

In [14]:
# create two numpy arrays, one 3x3, one 2x2
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [10, 11],
    [12, 13]
])

In [15]:
# use slicing to make the first 2 rows of a all 7s
a[:2] = 7

In [16]:
print(a)

[[7 7 7]
 [7 7 7]
 [7 8 9]]


In [11]:
# Slicing assignment actually also works with basic python lists:
l = [1, 2, 3, 4, 5]
# This works:
l[:2] = [7, 7]
print(l)

[7, 7, 3, 4, 5]


In [12]:
# BUT, with standard python lists, what it ACTUALLY does is cuts out the old slice,
# and puts the new list in its place.
# example: starting at index 3, cut out everything after it, and insert a new list in its place
l[3:] = [8, 7, 6, 5]
print(l)

[7, 7, 3, 8, 7, 6, 5]


In [17]:
# As you can see, the slice assignment for numpy arrays and python lists look similar,
# but they DO NOT do the exact same thing.
# with numpy arrays, the slice assignment will only change the values in the slices,
# while with python lists, it will CUT OUT the slice and put a new list in its place.

# Also, if you want to edit a 2D array, it's hard to do with lists, but easy with numpy arrays
# Example: 'paste' b into the first 2x2 section in a.
a[:2,:2] = b
print(a)

[[10 11  7]
 [12 13  7]
 [ 7  8  9]]


In [18]:
# This is extremely powerful, allowing you to edit entire chunks of arrays very easily.

## Reshaping NumPy arrays

We are going to list three main ways to reshape numpy arrays. We've talked about the 'reshape' and 'resize' methods in class, but there's also the 'ravel' method, which comes in handy sometimes.

In [19]:
# let's have a 1D array of integers with length 12
n = np.arange(12)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
# reshape:
# the reshape function will create a new array with the given shape.
# NOTE that it expects that the shape you give it will exactly match
# the total size of the old array, otherwise it will give an error, as we have seen in class.
n2 = n.reshape(4,3)
# print(n2)

In [31]:
# resize:
# the resize method actually changes the ORIGINAL array, instead of creating a new one
# it is also different from reshape because it does not give any errors
# if the new shape doesn't match the size of the old one.
# If the new shape is bigger, it will simply add zeros to fill the rest,
# and if the new shape is smaller, it will leave some of the original values out.

# NOTE: resizing an array that is referenced somewhere else might give an error,
# so we can pass in the argument refcheck=False to prevent that error
n.resize((7,2), refcheck=False)
print(n)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [ 0  0]]


In [33]:
# ravel:
# the ravel function simply unwraps a multi-dimensional array into 1D
# So it's like reshape, but only to turn an array 1D,
# and with the added convenience of not having to know the exact shape beforehand.
n = n.ravel()
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  0]


## Combining arrays

NumPy has many, many methods for combining arrays, but we'll just look at 2: append and concatenate.

In [36]:
# append:
# the append method simply inserts a bunch of values at the end of an array.
m = np.array([9, 10, 11, 12])
m = np.append(m, [13, 14, 15])
print(m)

[ 9 10 11 12 13 14 15]


In [39]:
# concatenate:
# the concatenate method takes a list of numpy arrays and tries to attach them together
# By default, it combines arrays row-wise:
x1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x2 = np.array([
    [7, 8, 9]
])
x = np.concatenate([x1, x2])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# but, if you give concatenate the argument axis=1,
# it will try to combine them column-wise (e.g. side to side)
# Example: combine our new x 2D array with our old 2D array a, side by side
ax = np.concatenate([a,x], axis=1)
print(ax)

[[10 11  7  1  2  3]
 [12 13  7  4  5  6]
 [ 7  8  9  7  8  9]]


## I/O: saving and loading numpy arrays from files

In order to make it easy to store a numpy array for later use, numpy gives some built in functions to easily save an array or multiple arrays to a file, and then read them from the file.

In [41]:
# saving a single array to a file:
# note: the .npy file extension is a convention indicating that this file has a numpy array in it.
a1 = np.array([1,2,3])
np.save('myarray.npy', a1)

In [42]:
# loading an array from a file:
a1 = np.load('myarray.npy')
print(a1)

[1 2 3]


In [43]:
# saving multiple arrays to a file:
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
np.savez('more_arrayz.npz', a2, a3)

In [45]:
# loading multiple arrays:
arrs = np.load('more_arrayz.npz')
print(arrs)

In [50]:
# this will give you a NpzFile object, which isn't directly useful.
# To get one array, use the index syntax [] on it and give the array name.
# The arrays are named 'arr_0', 'arr_1', etc., in the order you saved them.
a2 = arrs['arr_0']
print(a2)

[4 5 6]


In [51]:
# You can also choose to give your own names to the saved arrays when calling the savez function
# Use keyword arguments, the name you give the array will be what it's called when you load it
# Example: here, we are calling a2 'x', and a3 'y'
np.savez('keyword_arrayz.npz', x=a2, y=a3)

In [52]:
# Now, when you load the file, you can use the names you gave it instead of 'arr_0', etc.
arrs = np.load('keyword_arrayz.npz')
print(arrs['x'])

[4 5 6]
