# Multi-Variable Linear Regression

Last lecture we learned about linear regression, which is a simple method to find a correlation between an input (independent) and an output (dependent) variable. This is fine if your data only has a single independent variable, but the vast majority of real life data you might analyze will have numerous independent variables (and maybe even multiple dependent variables).

For these situations, simple linear regression is not good enough. We need to use **multi-variable linear regression** (also called multiple linear regression). As the name implies, it is a method that finds a correlation between multiple input variables and one output variable.

The formula for single variable linear regression is simply the equation of a line you should all know:
**y = w \* x + b**, where **x** is the input variable, **y** is the output variable, **w** is the weight (commonly known as the slope), and **b** is the bias (commonly known as the y-intercept)

The formula for multi-variable linear regression is:
**y = w_1 \* x_1 + w_2 \* x_2 + w_3 \* x_3 + ... + w_n \* x_n + b**
Here, **y** is still the output variable, same as before, but now we have *multiple* input variables: **x_1**, **x_2**, and so on all the way to **x_n** (you can literally have as many as you want). Of course, each input variable has its own weight, **w_1**, **w_2**, etc, up to **w_n**. And finally, **b**, the bias, is still the same.

In [1]:
import pandas as pd
import numpy as np

In [8]:
# like we did before, let's generate some fake data by starting with a known equation
# we will have 3 independent variables
def f(x1, x2, x3):
    return 2 * x1 + 3 * x2 + (-1) * x3 + 4

# as you can see from this equation, x1 and x2 both postively impact the output, with x2 having the most impact,
# while x3 actually negatively impacts output.

In [11]:
# create some random values in range 0-10 for each input variable (rounded to 2 decimals)
x1, x2, x3 = np.round(np.random.random((3,100)) * 10, decimals=2)

In [12]:
# take a look at one of the arrays to see what we've got:
x1

array([1.73, 7.6 , 6.83, 2.48, 6.81, 3.96, 3.83, 8.77, 4.41, 1.35, 4.94,
       6.79, 3.27, 0.6 , 5.68, 6.3 , 0.05, 3.21, 3.08, 6.02, 9.74, 9.13,
       3.34, 6.39, 0.52, 3.29, 3.17, 7.12, 7.98, 4.4 , 8.93, 8.37, 6.43,
       9.81, 0.69, 5.81, 8.88, 2.31, 7.89, 8.54, 2.18, 0.37, 5.65, 9.02,
       7.67, 6.31, 8.41, 5.93, 0.52, 1.15, 6.  , 7.39, 2.42, 2.21, 7.22,
       7.96, 4.08, 1.54, 3.14, 2.51, 1.31, 3.5 , 7.99, 2.75, 8.76, 5.04,
       3.08, 1.78, 7.9 , 5.49, 8.67, 2.25, 8.41, 5.64, 5.37, 7.07, 7.38,
       1.16, 7.15, 6.53, 3.62, 2.13, 0.73, 2.56, 3.01, 9.63, 9.48, 8.23,
       0.34, 8.34, 7.98, 3.46, 3.49, 3.57, 2.79, 1.46, 7.67, 8.98, 9.65,
       4.56])

In [44]:
# now create the output values.
# Note that these are 'perfect' outputs, without any error or residual at all
y = f(x1, x2, x3)
y

array([30.08, 33.12, 27.18,  3.25, 38.43, 16.38, 17.12, 23.7 , 17.53,
        4.89, 34.55, 40.35, 17.6 ,  0.33,  7.29, 28.64,  5.11, 35.2 ,
       26.65, 34.5 , 28.63, 29.16, 22.46, 43.23, 26.25, 23.62, 30.45,
       27.9 , 33.21, 25.05, 34.68, 40.96, 31.83, 35.77,  3.69, 37.16,
       41.16,  7.82, 40.32, 21.68, 29.6 , 24.96, 28.85, 33.07, 37.7 ,
       20.9 , 28.9 , 36.  , 22.49, 16.  , 28.76, 35.66,  9.69, 20.13,
       20.62, 31.91, 33.16,  6.95, 25.27,  8.27,  4.3 ,  5.6 , 21.  ,
       24.53, 43.92, 34.55, 14.81, 13.62, 30.35, 20.08, 12.01, 15.78,
       34.44, 43.41, 10.1 , 17.69, 27.77, 10.69, 34.7 , 34.39, 18.22,
       13.69, 11.74, 14.37,  6.21, 41.49, 23.15, 21.25, 25.71, 26.95,
       41.53, 22.89, 18.16, 27.16, 35.23, 19.72, 14.24, 23.37, 43.38,
       11.74])

In [45]:
# Now comes the important question:
# Given the 3 input arrays and 1 output array,
# how do we find the original equation?

# The answer is: not by hand, that's for damn sure.
# Introducing: sklearn, (full name: scikit-learn)
# This is by far one of the most used machine learning libraries in python
# We won't even be scratching the surface of its capabilities,
# For our purposes we just need a part of it, the linear_model submodule:
from sklearn import linear_model

In [46]:
# before we make the model, let's put our data in the expected format:
# pandas dataframe for the inputs, series for the output
inputs = pd.DataFrame({
    'x1': x1,
    'x2': x2,
    'x3': x3
})
output = pd.Series(y, name='output')

In [47]:
# Now we're ready to model.
# It's as simple as this:
# 1. create a new LinearRegression model
lr = linear_model.LinearRegression()
# 2. fit the data
lr.fit(inputs, output)
# 3. Done

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
# That's it. the regression model just did all the hard work,
# all that's left for you to do is analyze the results:

# check the r squared score, using LinearRegression.score():
print("r-squared: ", lr.score(inputs, output))
# of course, we expect a perfect score of 1.0, since this data is 100% linear

r-squared:  1.0


In [49]:
# check the coefficients using LinearRegression.coef_:
for i,coef in enumerate(lr.coef_):
    print(f"x{i}", np.round(coef, decimals=2))

x0 2.0
x1 3.0
x2 -1.0


In [50]:
# again, because this is a perfect linear dataset, the model found the exact coefficents
# check if it found the correct y-intercept as well (should be 4):
print(lr.intercept_)

3.9999999999999716


In [51]:
# Pretty much.

# having it predict this kind of 'perfect' data is no fun,
# let's toss in some random error in our output values.
output += np.random.normal(size=y.shape) # generate a normal distribution of error terms to add to the output

In [52]:
# now do the same modeling steps again
# we have to get a new LinearRegression model, because the old one has already been fitted with data
lr = linear_model.LinearRegression()
# fit the data
lr.fit(inputs, output)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [53]:
# check the score
lr.score(inputs, output)

0.9937176423000278

In [55]:
# as you can see, the r squared is still pretty high, but not a perfect 1 anymore
# same for the coefficients and intercept: they won't exactly match the originals
print(lr.coef_, lr.intercept_)

[ 1.96886701  3.03257995 -1.03013763] 4.086396384840132


In [59]:
# let's generate a new set of random input variables, and test our model to see how well it does
# we're lazy so we just copy the same code from before
x1, x2, x3 = np.round(np.random.random((3,100)) * 10, decimals=2)
inputs = pd.DataFrame({
    'x1': x1,
    'x2': x2,
    'x3': x3
})

In [ ]:
# create two output arrays:
# 1. the actual outputs, calculated directly from the true equation
y_actual = f(x1, x2, x3)
actual_output = pd.Series(y_actual, name="Actual Output")

In [70]:
# 2. the predicted outputs we get from our model, using the predict() function
y_predicted = lr.predict(inputs)
predicted_output = pd.Series(y_predicted, name="Predicted Output")
# you can compare them manually side-by-side in a dataframe:
compare = pd.concat([actual_output, predicted_output], axis=1)
compare = pd.DataFrame({
    'Actual Output': actual_output,
    'Predicted Output': predicted_output,
    'Residual': 
})

Actual Output  Predicted Output
0           41.97         41.850558
1           -3.09         -3.345400
2           19.58         19.598420
3           32.95         33.292888
4           26.61         26.494450
5           40.28         40.119621
6            6.85          6.498407
7           32.70         32.799097
8           36.03         35.936376
9           32.02         31.747884
10          28.04         27.838364
11          15.81         15.454881
12          13.07         12.907110
13          31.20         31.073834
14          11.76         11.794692
15          37.50         37.509380
16          28.42         28.179522
17          14.36         14.190391
18          36.16         36.108046
19          29.76         29.677679
20           4.37          4.315410
21          19.88         19.819456
22          47.51         47.533059
23          15.88         15.695233
24          40.53         40.433985
25          12.04         11.829669
26          16.17         16.037384
27          12.19         12.211438
28          20.54         20.429729
29          28.19         28.064522
..            ...               ...
70          42.31         42.328258
71          32.32         32.527257
72          35.67         35.638539
73           3.00          2.761584
74          46.73         46.800947
75          35.83         36.095191
76          11.46         11.384425
77          22.57         22.408546
78          36.22         36.234183
79          31.29         31.397146
80          11.62         11.443287
81          21.30         21.416506
82          30.73         30.888971
83          32.86         32.915815
84          16.39         16.137801
85          17.11         16.850617
86          19.70         19.439974
87          32.67         32.759096
88          15.80         15.666818
89          24.68         24.418522
90          40.60         40.528964
91          21.26         21.368584
92          37.28         37.118668
93          22.90         22.681186
94          37.25         37.169810
95          38.67         38.760974
96          38.43         38.515906
97          21.13         21.220339
98          30.47         30.294933
99          30.72         30.976784

[100 rows x 2 columns]

In [71]:
# It's a bit easier to compare if we add a column for the residuals
compare['Residual'] = compare['Predicted Output'] - compare['Actual Output']
compare

Actual Output  Predicted Output  Residual
0           41.97         41.850558 -0.119442
1           -3.09         -3.345400 -0.255400
2           19.58         19.598420  0.018420
3           32.95         33.292888  0.342888
4           26.61         26.494450 -0.115550
5           40.28         40.119621 -0.160379
6            6.85          6.498407 -0.351593
7           32.70         32.799097  0.099097
8           36.03         35.936376 -0.093624
9           32.02         31.747884 -0.272116
10          28.04         27.838364 -0.201636
11          15.81         15.454881 -0.355119
12          13.07         12.907110 -0.162890
13          31.20         31.073834 -0.126166
14          11.76         11.794692  0.034692
15          37.50         37.509380  0.009380
16          28.42         28.179522 -0.240478
17          14.36         14.190391 -0.169609
18          36.16         36.108046 -0.051954
19          29.76         29.677679 -0.082321
20           4.37          4.315410 -0.054590
21          19.88         19.819456 -0.060544
22          47.51         47.533059  0.023059
23          15.88         15.695233 -0.184767
24          40.53         40.433985 -0.096015
25          12.04         11.829669 -0.210331
26          16.17         16.037384 -0.132616
27          12.19         12.211438  0.021438
28          20.54         20.429729 -0.110271
29          28.19         28.064522 -0.125478
..            ...               ...       ...
70          42.31         42.328258  0.018258
71          32.32         32.527257  0.207257
72          35.67         35.638539 -0.031461
73           3.00          2.761584 -0.238416
74          46.73         46.800947  0.070947
75          35.83         36.095191  0.265191
76          11.46         11.384425 -0.075575
77          22.57         22.408546 -0.161454
78          36.22         36.234183  0.014183
79          31.29         31.397146  0.107146
80          11.62         11.443287 -0.176713
81          21.30         21.416506  0.116506
82          30.73         30.888971  0.158971
83          32.86         32.915815  0.055815
84          16.39         16.137801 -0.252199
85          17.11         16.850617 -0.259383
86          19.70         19.439974 -0.260026
87          32.67         32.759096  0.089096
88          15.80         15.666818 -0.133182
89          24.68         24.418522 -0.261478
90          40.60         40.528964 -0.071036
91          21.26         21.368584  0.108584
92          37.28         37.118668 -0.161332
93          22.90         22.681186 -0.218814
94          37.25         37.169810 -0.080190
95          38.67         38.760974  0.090974
96          38.43         38.515906  0.085906
97          21.13         21.220339  0.090339
98          30.47         30.294933 -0.175067
99          30.72         30.976784  0.256784

[100 rows x 3 columns]

In [72]:
# of course, as we've learned, we can compute our own r-squared score to see how the model did
# compute residual sum of squares (rss)
rss = np.sum(compare['Residual'].values ** 2)
rss

2.7393496599707725

In [73]:
# compute total sum of squares
tss = np.sum((y_actual - np.mean(y_actual)) ** 2)
tss

13002.003211

In [74]:
r_squared = 1 - rss / tss
r_squared

0.999789313260771

In [75]:
# A very high r_squared value, as we expected since there wasn't much error in the data.
# Of course, instead of computing this ourselves,
# we can let the LinearRegression.score() method do it for us:
lr.score(inputs, actual_output)

0.999789313260771

And that's pretty much it. That's how simple it is to create a multiple linear regression model, and test its effectiveness.

Here, we used fake data, but the idea behind using it on real data is exactly the same: you have a bunch of numerical input variables and a single numerical output variable, and you use the LinearRegression model to fit the data and generate predictions.

Notice the repetition of the word *numerical* above. Linear regression ONLY works on numerical data, which is why I emphasized the feature engineering step so much. If your dataset contains categorical data, you have to convert them into numerical data, either using direct integer encoding for ordinal data or one hot encoding for unordered data.